# In _config.yml
lsi: false
safe: true
#source: roy-ananya.github.io
name: Ananya Roy
url: roy-ananya.github.io
enforce_ssl: roy-ananya.github.io
title: Ananya Roy
description: Roy's Experiments, Learning and Rumination
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-hacker